### ISSUE TITLE
Consider renaming module

### ISSUE THREAD

**Issue by mourke** [siteline/SwiftUI-Introspect#130]
When exporting with swift evolution support, the interface files generated are corrupted because the module name "Introspect" collides with the enum named "Introspect" resulting in errors:

> Failed to build module 'Introspect' from its module interface; it may have been damaged or it may have triggered a bug in the Swift compiler when it was produced

> 'IntrospectionUIView' is not a member type of 'Introspect'

etc.

Maybe changing the module name to IntrospectKit? Or removing the enum altogether?

**Comment by freyaariel** [comment]
if you rename it, i recommend `SwiftUIIntrospection` instead of `IntrospectKit`, as it’s more specific and would go well in hand with Apple’s `DispatchIntrospection`.

**Comment by davdroman** [comment]
Thanks for letting us know @mourke, and thank you for the naming tip @freyaalminde. `SwiftUIIntrospection` sounds like a winner.

I'll make a PR soon to vend the library by this new name while retaining the old name as well for current users, as I wouldn't want anyone's imports to break due to this drastic change. Then for 1.0 we'll remove the vended "Introspect" products altogether.

**Comment by davdroman** [comment]
Update: the new module was released a few weeks ago and is now named [SwiftUIIntrospect](https://github.com/siteline/SwiftUI-Introspect#readme).
