### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by Urkman** [siteline/SwiftUI-Introspect#150]
Is this project still maintained?

**Comment by kylebrowning** [comment]
There's a release this year so yes?

**Comment by SplittyDev** [comment]
Hi, the project is alive and well.

We (@quintschaf) took over the maintenance of the project and we've shipped quite a few releases since Siteline stopped working on it. We're trying to keep the project somewhat up-to-date and ship fixes to existing issues whenever possible.

However, since the maintenance of Introspect is very time-consuming (thanks to numerous quirks in SwiftUI itself) and it's not our primary focus we're a bit behind on some things.

We're pretty much maintaining the project in our very limited free time, but PRs are always welcome.

**Comment by Urkman** [comment]
Great :) Thanks for your answer and maintaining the project 👍

**Comment by jevonmao** [comment]
Adding on to what everyone else said here, it's probably just about maintainers not having enough time and effort. i totally relate to splittydev, as i maintain some open source libraries myself. i'm not even a full time worker, i'm still a student and i can't imagine how people with full time jobs can squeeze enough time to struggle on maintaining open source projects - i love software but it's really on the bottom of my priorities

**Comment by joelpoloney** [comment]
CTO of Siteline here. If you think we should expand the set of maintainers on the project, please let us know! Happy to accommodate. We've paused our mobile development efforts but recognize how widely adopted this project is and want to continue to support. Let me know!

**Comment by davdroman** [comment]
@joelpoloney I think we might need some more maintainers in order to keep merging important changes such as #165 which seems to improve the reliability of this library a lot.

**Comment by ldiqual** [comment]
Good push @davdroman @jevonmao @Urkman
We'll begin to accept new maintainers, please comment in https://github.com/siteline/SwiftUI-Introspect/issues/58 if you're interested. Thank you!
