### ISSUE TITLE
CircleCI issues

### ISSUE THREAD

**Issue by SplittyDev** [siteline/SwiftUI-Introspect#179]
Hey @ldiqual, it looks like the CircleCI integration isn't working anymore.
Should we just remove it, or do you want to look into it?

We've been running the GitHub CI workflows alongside CircleCI for quite a while now, and it's been working fine, so theoretically there isn't really a need to keep CircleCI working anyway.

**Comment by davdroman** [comment]
@ldiqual this is blocking all PRs right now. From what I can see CircleCI auth may have been revoked for this repo so maybe the intention was to fully convert to GitHub Actions? If that's the case I can open a PR to remove the `/.circleci` directory altogether. I'd just like to get confirmation from you first.

<img width="904" alt="image" src="https://user-images.githubusercontent.com/2538074/216609004-f9707887-35b3-4473-9819-7f1907638c1a.png">

**Comment by joelpoloney** [comment]
Apologies for the delay on this one, everyone. I've removed the CircleCI config from the repo and disabled it in settings. Can you confirm that it's no longer causing issues? If so, just close this issue as resolved. Otherwise, let me know and I'll look into it further (CircleCI tends to stick its fingers in a few places... but I think I got em all).

**Comment by davdroman** [comment]
Thank you @joelpoloney! Though ci/circleci seems to still appear as part of the PR checks ([example](https://github.com/siteline/SwiftUI-Introspect/pull/168)) even after rebasing 🤔

Can you take a look please?

**Comment by davdroman** [comment]
All sorted. Wohoo! 🎉
