### ISSUE TITLE
introspectTextField becomeFirstResponder() broken

### ISSUE THREAD

**Issue by pmmlo** [siteline/SwiftUI-Introspect#19]
Using the latest version of Introspect 0.1.0, there seems to be a bug that does not allow you to select any field other than the first responder field.  When you tap into another field, it immediately refocuses on the first responder TextField.

Thinking I had a bug in my implementation, I looked back at another project from January 2020 that uses introspectTextField with becomeFirstResponder().  The implementation was identical.  Building the old project worked fine, and I was able to select another field without issue.  Looking at the Introspect version, it is 0.0.6.

On further investigation, this issue seems to have been introduced sometime in early February.  This might help us narrow down the version changes.

Here are a couple comments in Stackoverflow that also suggest this bug was introduced around early February: [Link to SO answer](https://stackoverflow.com/a/59277051/1909186)

Edit: Looking at the releases, there was only the one 0.1.0 release in February.  This makes it easier to isolate.

I will look through the changes since version 0.0.6, when I have time.

**Comment by pmmlo** [comment]
Since 0.0.6, it looks like there has been significant clean up, separating implementations for MacOS, tvOS, and Catalyst from iOS/iPadOS.

introspectTextField() now lives in ViewExtensions.swift.  On a quick review, the implementation seems to be abstracted to be the same, but it will take me some time to follow the logic.  My guess is there is some implicit logic behavior that is being overlooked by the abstractions.

Could one of the original engineers provide some insight?

**Comment by pmmlo** [comment]
Continuing to talk to myself, I downgraded to 0.0.6.  After cleaning the project and rebuilding, there is no issue with first responder on TextField now.  Before cleaning the project, it had the same "forced focus" behavior on one field.

After a couple rebuilds, I decided to clean, and it worked as expected.

**Comment by ldiqual** [comment]
@pmmlo I'm able to reproduce locally. Looking into what broke between 0.0.6 and 1.0.0. Thanks for your patience

**Comment by ldiqual** [comment]
@pmmlo Actually I'm not able to reproduce either on my phone or in the simulator – was looking at the wrong thing. I'm using the example project in the Simple Elements tab, which contains 2 textfields. Modified so that the first one becomes a first responder, but it didn't cause the bug above.

I do have a hunch of what is happening though. The introspect closure gets called on each element update, which might be triggered multiple times, including when selecting another element. So if you click on textfield 2, closure for textfield 1 might get called, which resets the first responder to textfield 1. We can solve that by adding introspection options like "only call closure once" or "call only on first update". I'd like to be able to reproduce locally first though.

Can you link me to a working example?

**Comment by pmmlo** [comment]
@ldiqual I agree with you.  I think it's something with the triggering and implicit execution of one of my modifiers.  I tried playing around with how I dismiss my keyboard but haven't had luck.

I tried both cocoapods and SPM.  Here's a gist: [gist](https://gist.github.com/pmmlo/64f26c8d0ea613d252a3e38da5f4c07f).
