### ISSUE TITLE
SwiftUI-Introspect not following SEMVER, causing dependency breakages

### ISSUE THREAD

**Issue by ggrell** [siteline/SwiftUI-Introspect#206]
Version `0.2.0` has a breaking change, setting the minimum iOS version to 13. Swift Packages should be following SEMVER, which requires that breaking changes bump the major version of the library. Please consider this in numbering the library releases.

Our project includes https://github.com/Amzd/ScrollViewProxy which has a dependency on this project, and so the 0.2.0 version ended up breaking our build indirectly. The workaround was to add an `exact` dependency on Introspect `0.1.4`. I've also suggested to that project to use `exact` versions for now (or upgrade to work with latest Introspec).

Thank you for your library! 🙏

**Comment by pyrtsa** [comment]
Quoting https://semver.org,

> 4. Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

**Comment by davdroman** [comment]
Exactly what @pyrtsa said. The library is by no means stable until 1.0. We're trying to remain as stable as possible, but in order to actually get to 1.0 we need to introduce some new constructs that might break some of the implicit contracts in the library.

Also note 0.2.0 is not the latest release. 0.2.3 is. Please update to this version and report back if you still have issues.

**Comment by ggrell** [comment]
Ah yes, I stand corrected, I forgot about the special case for sub v1.0! So probably best then to have `ScrollViewProxy` lock to a fixed version until this library hits 1.0 and will work with the maintainer there to correct it. Thanks again!
