### ISSUE TITLE
Cannot create own introspectable type in 0.4.0

### ISSUE THREAD

**Issue by xmanu** [siteline/SwiftUI-Introspect#227]
When trying to follow the instructions in the documentation, it is not possible to add a custom introspectable type, as the following compile error occurs:
`'PlatformViewVersion<Version, SwiftUIViewType, PlatformView>' initializer is inaccessible due to '@_spi' protection level`.

I guess this is because of the `@_spi(Internals)` annotation on the constructors in `PlatformViewVersion`. It would be nice to lift these restrictions, as it is cumbersome to fork the library just to add a custom instrospectable type.

**Comment by davdroman** [comment]
Hi @xmanu, thanks for reporting this.

Please note you can easily expose the required symbols as follows:

```swift
@_spi(Internals) import SwiftUIIntrospect
```

I forgot to add this line to the documentation, I shall do that shortly.

This SPI guarding is in fact by design, for a couple reasons:

1. During development, I found autosuggest unable to cope with platform version lookup while also having publicly available initializers. For some reason, it'd give up and just show the initializers instead, which isn't great. However marking them as SPI made this issue go away.
2. I'm hoping the explicit SPI annotation makes it so library developers will be more encouraged to PR their custom introspection code upstream.

Please let me know your thoughts.
