### ISSUE TITLE
.introspect(.searchField, on: ...) does not work in 0.4.0

### ISSUE THREAD

**Issue by xmanu** [siteline/SwiftUI-Introspect#228]
When introspecting a `.searchable` with the new introspect methods of 0.4.0, this does not work even when explicitly also searching in ancestors:
```
.introspect(.searchField, on: .iOS(.v16), scope: [.ancestor, .receiver]) { searchField in
    searchField.backgroundColor = .red
}
```
The "old" version works fine:
```
.introspectSearchController { searchController in
    searchController.searchBar.backgroundColor = .red
}
```

I unfortunately cannot easily test introducing a new `IntrospectableViewType` for a UISearchController because of #227.

**Comment by davdroman** [comment]
@xmanu funny enough, you've stumbled upon the one thing I knowingly wasn't able to get quite right 😄 🎯

Apart from my advice on #227 about SPI, I don't think you'll have luck implementing this yourself. I need to do some more thinking about how to introduce ancestor introspection beyond "look for a parent of X controller type", because that doesn't seem to cut it for this use case. Maybe it needs to be a fully custom lookup closure, but I'm not quite sure how that'd look yet, hence why I left it like that for now.

Fret not, this is on my mind. My next priority is to think of a more custom way to specify controller introspection and get back to you when it's ready.

**Comment by xmanu** [comment]
Wow that was fast! Amazing work on the new redesigned version btw. I like the explicit nature of supporting implementation differences in different iOS versions. Very clever! I already replaced all old calls (except for the searchBar/searchController) with the new syntax in our project and everything works well.

**Comment by davdroman** [comment]
@xmanu excellent! Was about to post about it here. Will tag release 0.5.0 shortly so you can peg it in your project. Good to hear it all works as expected now :)

**Comment by xmanu** [comment]
I will test replacing the rest of our introspected calls with 0.5.0. 

Is there any technical reason, that the new call returns the search bar and not the search controller? I have one place where I actually need the UISearchController to circumvent an internal SwiftUI bug...

**Comment by davdroman** [comment]
@xmanu yes, the reason is that `UISearchController` is actually not always guaranteed to exist (e.g. in a navigation stack's nav bar on iPad on iOS 15), so I decided to get down to view level which is always guaranteed.

You can always implement your own custom selector if you need the controller (bear in mind it won't work in some specific cases as mentioned):

```swift
@_spi(Internals) import SwiftUIIntrospect

extension iOSViewVersion<SearchFieldType, UISearchController> {
    @available(*, unavailable, message: ".searchable isn't available on iOS 13")
    public static let v13 = Self.unavailable()
    @available(*, unavailable, message: ".searchable isn't available on iOS 14")
    public static let v14 = Self.unavailable()
    public static let v15 = Self(for: .v15, selector: selector)
    public static let v16 = Self(for: .v16, selector: selector)

    private static var selector: IntrospectionSelector<UISearchController> {
        .from(UINavigationController.self) {
            $0.navigationBar.topItem?.searchController
        }
    }
}
```

Not sure if the extension will clash with the existing one, so you might need to disambiguate it by specifying the type in the closure:

```swift
.introspect(.searchField, on: .iOS(.v15, .v16)) { (searchController: UISearchController) in
	...
}
```

**Comment by xmanu** [comment]
That is a very valid reason! I will probably introduce a new type so I can call `.introspect(.searchController, ...` and prevent the typing clash. But this is probably not a good idea to include in the library I guess...

**Comment by davdroman** [comment]
@xmanu yeah it was a tough call. Ultimately I think prioritizing predictability is best, with users having the option to dip into more nuanced territory via custom selectors. Good shout introducing the new type, sounds sensible 👍
