### ISSUE TITLE
How to use findAncestor?

### ISSUE THREAD

**Issue by riccardo-lomazzi** [siteline/SwiftUI-Introspect#29]
Suppose I'd want to save the `contentOffset` of a `UITableView` whenever I click an element inside of it.
E.g.

```swift
List {
    ForEach(items, id: \.self) { element in
         Button(element) {
             navigation.contentOffset = // get tableview contentOffset
         }
    }
}
```

How can I use `findAncestor` to get the parent `UITableView`'s `contentOffset`?
I've tried using this
```swift
Introspect.findAncestor(ofType: UITableView, from: UIButton) as? UITableView
```
but the compiler returns:
```swift
Cannot convert value of type 'UIButton.Type' to expected argument 'PlatformView' (aka 'UIView')
```

I've already tried using a `UILabel` instead of `UIButton` and it gives me the same error.

**Comment by end3r117** [comment]
Couple things. You should provide a Type for the "ofType" parameter: `UITableView.self`. The error you're getting is because you need to pass an _instance_ of a PlatformView to the function, not the type.

Not sure where you're trying to use that Introspect.findAncestor static function, but for this use case, you should just introspect from within the view hierarchy. Using your example, you could try something like this:

```
@EnvironmentObject var navigation: NavigationCoordinator
@ObservedObject var viewModel = ViewModel

var body: some View {
    List {
        ForEach(viewModel.items, id: \.self) { element in
             Button(element) {
                 self.navigation.contentOffset = viewModel.listOffset
             }
        }
    }
    .introspectTableView { tableView in
        self.viewModel.listOffset = tableView.contentOffset
    }
}
```

**Comment by SplittyDev** [comment]
This doesn't seem to be an Introspect bug and the issue hasn't had any activity for months, therefore I'll go ahead and close it.
