### ISSUE TITLE
MacOS 15 support?

### ISSUE THREAD

**Issue by ukushu** [siteline/swiftui-introspect#435]
### Description

No ability to use lib with macOS 15 (ScrollView introspect supported only for macOS 14 maximum)

### Checklist

- [X] I have read the [README](https://github.com/siteline/swiftui-introspect#swiftui-introspect) before submitting this report.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/siteline/swiftui-introspect/issues) or [discussion](https://github.com/siteline/swiftui-introspect/discussions).

### Version information

2c6b476

### Destination operating system

macOS 15.0

**Comment by SplittyDev** [comment]
Well, I wanted to take a look at this and update tests for macOS 15 to see what works and what doesn't, but turns out, David managed to make this project essentially unmaintainable before he decided that he doesn't have time to maintain it anymore.

The generic platform version predicate makes it _impossible_ to reuse any code between tests or even between different versions of the same view, and looking at the sheer amount of test cases, I'd estimate that it would take _hours_ of mindless copy-pasting to add the `.v15` case to all of them..

I'm sorry, but I really don't have the time to fix this mess. I can't even believe the code I'm looking at here. Who comes up with something like that?!

Anyway, I actually did fix the tests for `ScrollView` on macOS 15 (locally on my machine), and they pass. Looking at the code, the `ScrollView` `macOSViewVersion` extension supports the `v15` case as well.

Maybe the version that has macOS 15 support hasn't been released yet? I'm not quite sure, but maybe targeting the `main` branch fixes your issues.

**Comment by SplittyDev** [comment]
@ukushu What is it you wanna do with the ScrollView? SwiftUI has added lots of stuff that's now natively possible, maybe Introspect isn't even needed anymore..

If you really need introspection, you can take a look at https://github.com/fivesheepco/swiftui-inspect, which is our rewrite of Introspect with a cleaner API. It should do the trick just fine for accessing the inner `NSScrollView`.

**Comment by SplittyDev** [comment]
> All I need is just to get instance of ScrollView

Using the SwiftUI-Inspect library I linked you should be able to just do this:
```swift
ScrollView {
  // ...
}.inspect { view in
  model.sw = view
}
```

**Comment by ukushu** [comment]
@SplittyDev  what about window access? 

         .introspect(.window, on: .macOS(.v12,.v13,.v14,v15)) {
            model.wnd = $0
        }

**Comment by SplittyDev** [comment]
> @SplittyDev what about window access?

Window access isn't a feature we're planning to support. Our library is restricted to `NSView` and `UIView` instances, and `NSWindow` falls outside of that. It would be very hard to do interface-wise too, because we expose a simple `.inspect` function on every supported view.

For example:
```swift
Button("foo", action: {})
  .inspect { view in /* NSButton */ }
```

For the window, we'd have to do something completely different, as we can't simply expose an `inspect` method on every `View` to access the Window. It doesn't fit well into the library.

But you can always do something like this:

```swift
// The window currently receiving keyboard events
let keyWindow: NSWindow? = NSApplication.shared.keyWindow

// The main window of the app
let mainWindow: NSWindow? = NSApplication.shared.mainWindow
```
