### ISSUE TITLE
Question : Is this good practice ?

### ISSUE THREAD

**Issue by x4080** [siteline/SwiftUI-Introspect#65]
Hi, if I wanted to store the underlying view inside a variable that can be accessed later, is below code good practice ?
```swift
struct ContentView: View {
    @State var content: String = ""
    @State var _textField:UITextField?

...
TextField("Content", text: $content)
.introspectTextField { textField in
                            print("debug")
                            _textField=textField
  }    
```
so that later I can call that _textField?.becomeFirstResponder() like

```swift
Button(action: {
    _textField?.becomeFirstResponder()
}) {
    Text("Focus it")
}
```

Will the _textField become memory leak ?

Thanks for answering

**Comment by MohammadNjf** [comment]
Perhaps it's better to keep a weak reference

**Comment by JannThomas** [comment]
Hi @x4080, that hugely depends somehow on how you use it. In your ContentView, if this is the main struct of the app, it will obviously never be removed, but that is also expected, right? Also, if you store a view behaving like this somewhere, it will also never be initialized, but that is rather a problem with that code then.

Assuming it is a view that gets shown and also disappears at some point, it depends on the underlying structure of SwiftUI. That said the structure would have to be very strange for this to become a memory leak.

I have tested this with the current version of SwiftUI in Xcode 12.4 and iOS 12.4 with the following Code:
```
struct ContentView: View {
    
    @State var isModalShowing = false
    
    var body: some View {
        Text("Hello, World!")
            .onTapGesture {
                self.isModalShowing.toggle()
            }
            .sheet(isPresented: $isModalShowing) {
                ModalView()
            }
        
    }
}

class TestObject {
    init() {}
    
    deinit {
        print("deinitialized")
    }
}

struct ModalView : View {
    
    @State private var usernmae =  "hello"
    @State var textField: UITextField?
    @State var testObject: TestObject?
    
    var body : some View {
        VStack(alignment: .leading) {
            TextField("test", text: $usernmae)
                .introspectTextField { textField in
                    print("setting:", textField)
                    self.textField = textField
                    self.testObject = TestObject()
                }
            
        }
        .padding(.horizontal, 50)
    }
}
```

It prints:
```
setting: <SwiftUI.SwiftUITextField: 0x16090a800; baseClass = UITextField; frame = (0 0; 290 22); text = 'hello'; opaque = NO; gestureRecognizers = <NSArray: 0x60000073e0d0>; placeholder = test; borderStyle = None; background = <_UITextFieldNoBackgroundProvider: 0x600000bb4af0: textfield=<SwiftUI.SwiftUITextField 0x16090a800>>; layer = <CALayer: 0x600000904320>>

deinitialized
```

Seeing that the `deinitialized` does get printed when the view is dismissed, the current version of SwiftUI will not create a memory leak because of this practice.

I hope this answers your question. I will close this issue for now.

PS: @MohammadNjf's solution doesn't work since state variables cannot be weak. You could create an object that has a weak reference to it though.

**Comment by x4080** [comment]
@JannThomas Thanks
