### ISSUE TITLE
NavigationView Introspection with a NavigationViewStyle

### ISSUE THREAD

**Issue by Pandawan** [siteline/SwiftUI-Introspect#74]
I'm trying to prevent a navigation flow from using the iPad detail/two-column layout and instead use a stack navigation layout like it does on iPhone. For this I need to use `.navigationViewStyle(StackNavigationViewStyle())`; however, this seems to conflict with `.introspectNavigationController`. When I have both of them on at the same time, the navigation style is properly used, yet the introspect closure is never called. The instant I remove `.navigationViewStyle`, the introspect starts working again.

Here's a small reproducible example:
```swift
struct TestNavigationView: View {
    var body: some View {
        NavigationView {
            NavigationLink("Go To View", destination: Text("Subview"))
        }
        // Disable the "split view" (aka Detail View) layout on iPad
        .navigationViewStyle(StackNavigationViewStyle())
        .introspectNavigationController() { navigationController in
            // This is not called unless the .navigationViewStyle call above is commented out
            print("Introspect called with navigationController \(navigationController.debugDescription)")
        }
        .onAppear() {
            // This is called
            print("View does show up")
        }
    }
}
```

I might be wrong as I don't have much experience with UIKit, but it might be that the .navigationViewStyle changes what underlying UIKit view is rendered since the [iPad two-column-style navigation view](https://developer.apple.com/documentation/uikit/uisplitviewcontroller) is different from the [typical NavigationViewController](https://developer.apple.com/documentation/uikit/uinavigationcontroller). Still this doesn't explain why this also fails to work on iPhone, since it shouldn't be using a UISplitViewController anyway.

Perhaps I can temporarily circumvent this with a custom introspect, or something else?

**Comment by mokkun** [comment]
So I also ran into this issue and spent some time trying to figure out what the cause could be. I'm not very experienced with UIKit or iOS development by all means, so I can't fully understand all the code.

The first thing I did was to compare the hierarchy, since as you suggested, maybe the `navigationViewStyle` would change the underlying view.

| Default | Stacked |
|----|----|
| <img width="490" alt="Screen Shot 2021-03-22 at 19 20 31" src="https://user-images.githubusercontent.com/44582/111983893-00ad4f00-8b4e-11eb-8d5a-ea2a0b79c862.png"> | <img width="497" alt="Screen Shot 2021-03-22 at 19 21 12" src="https://user-images.githubusercontent.com/44582/111983961-1a4e9680-8b4e-11eb-8dcb-2e521fd0d5c1.png"> |

So in the default case, the `ViewHost` has a `NotificationSendingSplitViewController` as a child, and a few more until it reaches the `UINavigationController`, while the stacked version doesn't.

Looking at the code, the `introspectNavigationController` function will [search for siblings](https://github.com/siteline/SwiftUI-Introspect/blob/master/Introspect/ViewExtensions.swift#L42). The logic in the `previousSibling` ensures that there is a parent with children and [then iterates on each child children](https://github.com/siteline/SwiftUI-Introspect/blob/master/Introspect/Introspect.swift#L151) to find a match.

When I put a breakpoint in that loop, I've noticed the `child` was of type `UINavigationController` when using the stacked style. 

| Default |
|---|
| <img width="563" alt="Screen Shot 2021-03-22 at 20 06 00" src="https://user-images.githubusercontent.com/44582/111997281-3bb77e80-8b5e-11eb-81b7-6211539ce15e.png"> |

| Stacked |
|---|
| <img width="530" alt="Screen Shot 2021-03-22 at 20 07 10" src="https://user-images.githubusercontent.com/44582/111997304-440fb980-8b5e-11eb-9f28-3302bb229d1e.png"> |

So the call for `findChild(ofType: type, in: child)` will not return anything, because `child` is the `UINavigationController` that we want to be returned. But the current code has no checks for it, as far as I could understand.

I've changed the for loop to check if `child` is of the expected type and return:

```swift
for child in parent.children[0..<entryIndex].reversed() {
    if let typed = child as? AnyViewControllerType {
        return typed
    }
    if let typed = findChild(ofType: type, in: child) {
        return typed
    }
}
```

This seems to fix the issue, I could use `navigationViewStyle(StackNavigationViewStyle())` normally. That said, I'm not confident that the above is the best way of fixing this, nor that it doesn't break anything else. 😬 

If the collaborators of the project see this and give some input, I'll gladly make a PR with a fix. For the time being, you can try this yourself locally and see if it works.

**Comment by mokkun** [comment]
In case you are looking for an extension, maybe the following can help:

```swift

extension View {
  public func introspectStackNavigationController(customize: @escaping (UINavigationController) -> ()) -> some View {
    return inject(UIKitIntrospectionViewController(
      selector: { introspectionViewController in
        if let navigationController = introspectionViewController.navigationController {
          return navigationController
        }

        // This is the same code you can find in `previousSibling()`.
        let entry = introspectionViewController
        guard let parent = entry.parent,
        let entryIndex = parent.children.firstIndex(of: entry),
        entryIndex > 0
        else {
          return nil
        }
        
        // First child should be our navigation controller.
        if let navigationController = parent.children[0] as? UINavigationController {
          return navigationController
        }
        return nil
      },
      customize: customize
    ))
  }
}
```

Usage:

```swift
struct ContentView: View {
    var body: some View {
        NavigationView {
            ...
        }
        .navigationViewStyle(StackNavigationViewStyle())
        .introspectStackNavigationController { controller in
            controller.navigationBar.backgroundColor = UIColor.blue
        }
}
```

**Comment by JannThomas** [comment]
Hi, the `introspectNavigationController` function should be used inside the NavigationView. This has to do with the underlying SwiftUI-generated view structure and is documented as the function documentation summary:

```
Finds a UINavigationController from any view embedded in a SwiftUI.NavigationView.
```
