### ISSUE TITLE
Tackling SwiftUI view layout randomness

### ISSUE THREAD

**Issue by JannThomas** [siteline/SwiftUI-Introspect#93]
Hi @ldiqual, @SplittyDev,

We get a lot of Issues like #73, stating that something doesn't work under certain conditions. A few days ago, I merged #83, tackling exactly this kind of problem, but not in an ideal way. At that time I thought this behavior just occurred for TextField and wasn't a systemic issue. Now there's a few options here that we could consider. The ones I have come up with are:

1. Leave everything as it is, let people run into these problems and find a solution case by case, but there is not always a solution.
2. Add detection of when an introspection fails and print a message with useful tips, like trying to use the introspect function somewhere else. (Since there is not always a solution, that doesn't really solve everything)
3. Change the underlying architecture so it always uses the approach from #83. I do believe this is somewhat of a hacky solution though and might, in the cases it doesn't work the normal way, introduce latency as the entire view hierarchy will be traversed from bottom to top and down again.
4. Enable the change from #83 with a boolean or enum case on every introspect method, but add a default value for that parameter being the current approach. That way we can solve the issue in cases it doesn't work, but don't introduce latency when it shouldn't be there. Also we could document that the traversing approach should not be used if not necessary.

It would also be possible to combine options 4 and 2.

I would like to back my claim that there is not always a solution without using the code that I added by giving this example:
```swift
var body: some View {
    VStack {
        TextField(textField1Placeholder, text: $textFieldValue)
        .introspectTextField { textField in
            self.spy1(textField)
        }
        TextField(textField2Placeholder, text: $textFieldValue)
        .introspectTextField { textField in
            self.spy2(textField)
        }
        TextField(textField3Placeholder, text: $textFieldValue)
        .introspectTextField { textField in
            self.spy3(textField)
        }
    }
    .cornerRadius(8)
}
```
You can add the introspectTextField method after the .cornerRadius here and it will work, but you will only ever get the first text field.

Would love to hear both of your opinions on this. @ldiqual I thought you would like to be notified of this since any decision here is a pretty big one.

**Comment by SplittyDev** [comment]
I think going for a combination of 2 and 4 could be a good solution here.

That way the user gets to decide whether he wants to use the "deep" search instead of the regular one and at the same time we can actually point the user in this direction by logging this tip to the console in case a view is not found.

Should make life easier for the user and also for us.

**Comment by joshuakcockrell** [comment]
Just my opinion, but I would love to see more strict requirements on the location of the `.introspect()` calls across this library. (something like) it needs to be directly after the element you're inspecting or it doesn't work. 

It's scary that something changing in the view hierarchy could result in a "deep" search that would return an element far away from the one intended.

That's what happened with my issue https://github.com/siteline/SwiftUI-Introspect/issues/139 . I added a `.cornerRadius` and suddenly my `.introspectScrollView` was returning something ~10 levels up the hierarchy. No warning message, no nil response, just a super buggy `ScrollView` being controlled by something 10 levels down. I would much prefer a nil response and print saying, "No ScrollView found within the parent superview"

Thanks for all you do!

**Comment by joshuakcockrell** [comment]
After working the past day to try and figure out https://github.com/siteline/SwiftUI-Introspect/issues/139 , I would prefer this library took the search-up-the-ancestor-tree approach as default for SwiftUI elements that have nested content. Seems more reliable for `ScrollView`, `List`, `NavigationView`, etc.

Tell people to put the introspect method inside the content (like what I did in https://github.com/siteline/SwiftUI-Introspect/issues/139 ) and default to an ancestor search. Hopefully that would avoid a lot of broken sibling searches. I haven't really experimented though to see how reliable this approach is, and it wouldn't fix things like the broken `TextField` searches.. but hopefully it would eliminate a host of issues with sibling searches.

**Comment by davdroman** [comment]
I appreciate this is a very old thread, but as a new maintainer of this project I'm doing my very best to stabilize the behavior of this library and make it as predictable as possible. After tagging a new release with a bunch of stale PRs I merged recently I'm going to take a stab at what @joshuakcockrell suggested:

> I would prefer this library took the search-up-the-ancestor-tree approach as default for SwiftUI elements that have nested content. Seems more reliable for `ScrollView`, `List`, `NavigationView`, etc.

This is also more in line with how SwiftUI works for most `navigationXYZ` and `listXYZ` modifiers — they only work when applied to the content, not the view itself.

In general, I think we should attempt to stabilize the library as much as possible and have a myriad of complex unit tests and better documentation. However I wouldn't want to break current behavior for existing users, so I'd probably opt in for doing a 1.0 release.

How does all of this sound?

**Comment by davdroman** [comment]
For anyone interested[^1], I wanted to let you know that I released [a brand new module](https://github.com/siteline/SwiftUI-Introspect/blob/master/docs/SwiftUIIntrospect.md) a few weeks ago which revamps the original implementation and API to be a lot more stable, predictable and ergonomic (and support iOS 17!).

A number of issues in the original Introspect module (like the ones mentioned by the OP above) are now a thing of the past.

The new introspection mechanism is extremely accurate because it acts on the target view directly by ["sandwiching"](https://github.com/siteline/SwiftUI-Introspect/blob/master/docs/SwiftUIIntrospect.md#how-it-works) it, which eliminates the possibility of finding neighboring views of the same type by mistake even in most complex of hierarchies.

So, contrary to my initial guess in the post above, it's looking up the ancestor tree that is now explicitly opt-in, and it should be quite rarely needed by my estimation.

I'd love to know your thoughts on the new module whenever you get a chance to try it out.

[^1]: Explicit mention to @joshuakcockrell @AmadeusK525 since they reacted to my original message above.

**Comment by davdroman** [comment]
Closing this but anyone feel free to add more comments below.
